### ISSUE TITLE
Bug Report: _onTimeout not handling write() error

### ISSUE THREAD

**Issue by banchanKiro** [xpepermint/smtp-channel#13]
The error handling for the write() function on the _onTimeout function is not done.
When the socket times out, and it tries to send the QUIT command automatically, it gives out a 'Socket has closed unexpectedly' error.
But this is not handles in the function, which is causing my application to crash.

**Comment by xpepermint** [comment]
https://github.com/xpepermint/smtp-channel/pull/14
