### ISSUE TITLE
TypeError: Cannot read property 'removeListener of null

### ISSUE THREAD

**Issue by LMCv3** [xpepermint/smtp-channel#2]
Hi!

We regularly get this error on a server that's opening / trying a number of connections, and on occasion the network socket will close unexpectedly or the connection will be reset before we're finished. Here's the output:

```
/xxxx/node_modules/smtp-channel/src/index.js:244
      this._socket.removeListener('error', onError);
                  ^

TypeError: Cannot read property 'removeListener' of null
    at Socket.onClose (/xxxx/node_modules/smtp-channel/src/index.js:244:19)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)

https://github.com/xpepermint/smtp-channel/blob/299d078fc3fc2da5e91abf38827ffe3a2d8683be/src/index.js#L244
```
Running Node v6.9.1 on Ubuntu Xenial

**Comment by kingkong404** [comment]
+1

**Comment by xpepermint** [comment]
Hey guys, sorry for my late reply. My todo has a long list of tasks :). I ran tests again and it works. Can you provide a full project code so I can check the whole code?

**Comment by ArsenyYankovsky** [comment]
Could you please release the a new with the fix? @xpepermint

**Comment by xpepermint** [comment]
Done: smtp-channel@0.2.3
