### ISSUE TITLE
[FR] Socks proxy support (or providing external socket object)

### ISSUE THREAD

**Issue by nemanjan00** [xpepermint/smtp-channel#4]
There is missing support for using socks proxy to talk to SMTP proxy. 

I do plan to implement this today, just wanted to ask if you have any special requests. 

I plan to use this lib: 

https://www.npmjs.com/package/socks

**Comment by nemanjan00** [comment]
Also, would appreciate merging #3

**Comment by xpepermint** [comment]
Done, thx.
